// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PIV_PROYECTO_Final.Models;

#nullable disable

namespace PIV_PROYECTO_Final.Migrations
{
    [DbContext(typeof(MUSICAL_AVANZADAContext))]
    partial class MUSICAL_AVANZADAContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AspNetUserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex(new[] { "RoleId" }, "IX_AspNetUserRoles_RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("PIV_PROYECTO_Final.Models.AspNetRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NormalizedName" }, "RoleNameIndex")
                        .IsUnique()
                        .HasFilter("([NormalizedName] IS NOT NULL)");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("PIV_PROYECTO_Final.Models.AspNetRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "RoleId" }, "IX_AspNetRoleClaims_RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("PIV_PROYECTO_Final.Models.AspNetUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "IX_AspNetUserClaims_UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("PIV_PROYECTO_Final.Models.AspNetUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex(new[] { "UserId" }, "IX_AspNetUserLogins_UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("PIV_PROYECTO_Final.Models.AspNetUserToken", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("PIV_PROYECTO_Final.Models.CANCIONES_USUARIO", b =>
                {
                    b.Property<int>("ID_CANCIONES_USUARIO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_CANCIONES_USUARIO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_CANCIONES_USUARIO"), 1L, 1);

                    b.Property<int>("ESTADO")
                        .HasMaxLength(450)
                        .HasColumnType("int")
                        .HasColumnName("ESTADO");

                    b.Property<string>("ID_CANCION")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ID_CANCION");

                    b.Property<string>("ID_USUARIO")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ID_USUARIO");

                    b.HasKey("ID_CANCIONES_USUARIO")
                        .HasName("PK__CANCIONE__07E3F772C02EBF6E");

                    b.HasIndex("ID_CANCION");

                    b.ToTable("CANCIONES_USUARIO", "SCH_MUSICAL_AVANZADA");
                });

            modelBuilder.Entity("PIV_PROYECTO_Final.Models.GeneroMusical", b =>
                {
                    b.Property<string>("CodigoGenero")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CODIGO_GENERO");

                    b.Property<string>("DescripcionGenero")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("DESCRIPCION_GENERO");

                    b.HasKey("CodigoGenero");

                    b.ToTable("GENERO_MUSICAL", "SCH_MUSICAL_AVANZADA");
                });

            modelBuilder.Entity("PIV_PROYECTO_Final.Models.ModuloCancione", b =>
                {
                    b.Property<string>("CodigoCancion")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CODIGO_CANCION");

                    b.Property<string>("CodigoGenero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CODIGO_GENERO");

                    b.Property<string>("NombreCancion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("NOMBRE_CANCION");

                    b.Property<decimal>("PrecioCancion")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("PRECIO_CANCION");

                    b.HasKey("CodigoCancion");

                    b.HasIndex("CodigoGenero");

                    b.ToTable("MODULO_CANCIONES", "SCH_MUSICAL_AVANZADA");
                });

            modelBuilder.Entity("PIV_PROYECTO_Final.Models.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Genero")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValueSql("(N'NUll')");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NombreCompleto")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasDefaultValueSql("(N'NUll')");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NumeroTarjeta")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("(N'NUll')");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoTarjeta")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasDefaultValueSql("(N'NUll')");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasDefaultValueSql("(N'Null')");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NormalizedEmail" }, "EmailIndex");

                    b.HasIndex(new[] { "NormalizedUserName" }, "UserNameIndex")
                        .IsUnique()
                        .HasFilter("([NormalizedUserName] IS NOT NULL)");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("PIV_PROYECTO_Final.Models.VentaCancione", b =>
                {
                    b.Property<string>("NumeroFactura")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("NUMERO_FACTURA");

                    b.Property<DateTime>("FechaCompra")
                        .HasColumnType("datetime")
                        .HasColumnName("FECHA_COMPRA");

                    b.Property<int>("IdCancionesUsuario")
                        .HasColumnType("int")
                        .HasColumnName("ID_CANCIONES_USUARIO");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("SUBTOTAL");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("TOTAL");

                    b.Property<string>("UsuariosIdentificacion")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)")
                        .HasColumnName("USUARIOS_IDENTIFICACION");

                    b.HasKey("NumeroFactura");

                    b.HasIndex("IdCancionesUsuario");

                    b.ToTable("VENTA_CANCIONES", "SCH_MUSICAL_AVANZADA");
                });

            modelBuilder.Entity("AspNetUserRole", b =>
                {
                    b.HasOne("PIV_PROYECTO_Final.Models.AspNetRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PIV_PROYECTO_Final.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PIV_PROYECTO_Final.Models.AspNetRoleClaim", b =>
                {
                    b.HasOne("PIV_PROYECTO_Final.Models.AspNetRole", "Role")
                        .WithMany("AspNetRoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PIV_PROYECTO_Final.Models.AspNetUserClaim", b =>
                {
                    b.HasOne("PIV_PROYECTO_Final.Models.Usuario", "User")
                        .WithMany("AspNetUserClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PIV_PROYECTO_Final.Models.AspNetUserLogin", b =>
                {
                    b.HasOne("PIV_PROYECTO_Final.Models.Usuario", "User")
                        .WithMany("AspNetUserLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PIV_PROYECTO_Final.Models.AspNetUserToken", b =>
                {
                    b.HasOne("PIV_PROYECTO_Final.Models.Usuario", "User")
                        .WithMany("AspNetUserTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PIV_PROYECTO_Final.Models.CANCIONES_USUARIO", b =>
                {
                    b.HasOne("PIV_PROYECTO_Final.Models.ModuloCancione", "IdCancionNavigation")
                        .WithMany("CancionesUsuarios")
                        .HasForeignKey("ID_CANCION")
                        .IsRequired()
                        .HasConstraintName("FK_CANCIONES_USUARIO_CANCION");

                    b.Navigation("IdCancionNavigation");
                });

            modelBuilder.Entity("PIV_PROYECTO_Final.Models.ModuloCancione", b =>
                {
                    b.HasOne("PIV_PROYECTO_Final.Models.GeneroMusical", "CodigoGeneroNavigation")
                        .WithMany("ModuloCanciones")
                        .HasForeignKey("CodigoGenero")
                        .IsRequired()
                        .HasConstraintName("FK_MODULO_CANCIONES_CODIGO_GENERO");

                    b.Navigation("CodigoGeneroNavigation");
                });

            modelBuilder.Entity("PIV_PROYECTO_Final.Models.VentaCancione", b =>
                {
                    b.HasOne("PIV_PROYECTO_Final.Models.CANCIONES_USUARIO", "IdCancionesUsuarioNavigation")
                        .WithMany("ModuloVentaCancione")
                        .HasForeignKey("IdCancionesUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_VENTA_CANCIONES_ID_CANCIONES_USUARIO");

                    b.Navigation("IdCancionesUsuarioNavigation");
                });

            modelBuilder.Entity("PIV_PROYECTO_Final.Models.AspNetRole", b =>
                {
                    b.Navigation("AspNetRoleClaims");
                });

            modelBuilder.Entity("PIV_PROYECTO_Final.Models.CANCIONES_USUARIO", b =>
                {
                    b.Navigation("ModuloVentaCancione");
                });

            modelBuilder.Entity("PIV_PROYECTO_Final.Models.GeneroMusical", b =>
                {
                    b.Navigation("ModuloCanciones");
                });

            modelBuilder.Entity("PIV_PROYECTO_Final.Models.ModuloCancione", b =>
                {
                    b.Navigation("CancionesUsuarios");
                });

            modelBuilder.Entity("PIV_PROYECTO_Final.Models.Usuario", b =>
                {
                    b.Navigation("AspNetUserClaims");

                    b.Navigation("AspNetUserLogins");

                    b.Navigation("AspNetUserTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
